using System.Globalization;
using System.Net;
using System.Text;
using Elevate.Audit.Model;

namespace Elevate.Audit.Rendering;

/// <summary>One self-contained HTML file: inline CSS from report.css, no external requests, one h1, https links only.</summary>
public static class HtmlRenderer
{
    internal const string StylesheetResource = "Elevate.Audit.Resources.report.css";
    internal const string ScriptResource = "Elevate.Audit.Resources.report.js";

    private static readonly Lazy<string> StylesheetText = new(() => ReadResource(StylesheetResource, "report.css"));
    private static readonly Lazy<string> ScriptText = new(() => ReadResource(ScriptResource, "report.js"));

    public static string Stylesheet => StylesheetText.Value;
    public static string Script => ScriptText.Value;

    private static string ReadResource(string name, string file)
    {
        using var stream = typeof(HtmlRenderer).Assembly.GetManifestResourceStream(name) ?? throw new InvalidOperationException($"{file} missing from the bundle");
        using var reader = new StreamReader(stream, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private const string Caret = "<svg class=\"caret\" viewBox=\"0 0 20 20\" fill=\"none\" stroke=\"#526176\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M8 6l4 4-4 4\"/></svg>";

    private static readonly (string Source, string Name, string Note)[] CoverageSources =
    [
        ("entra", "Entra role assignments", "Every active assignment and eligibility."),
        ("groups", "Groups", "Members of role-assigned groups, nested groups included."),
        ("pim-for-groups", "PIM for Groups", "Active and eligible memberships of PIM-managed groups."),
        ("azure", "Azure subscriptions", "Role assignments in the subscriptions the account can read."),
        ("azure-management-groups", "Azure management groups", "Role assignments inherited from management groups."),
        ("principals", "Principals", "Names, sign-in names and guest status."),
    ];

    public static string Render(AuditReport report)
    {
        ArgumentNullException.ThrowIfNull(report);
        var b = new StringBuilder(128 * 1024);
        var tenantName = report.Tenant.DisplayName ?? report.Tenant.Id;
        b.Append("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\" />\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n<meta name=\"robots\" content=\"noindex\" />\n");
        b.Append("<title>").Append(E($"Standing access report — {tenantName}")).Append("</title>\n<style>\n").Append(Stylesheet).Append("\n</style>\n</head>\n<body>\n");

        Header(b, report, tenantName);

        b.Append("<main class=\"wrap\">\n");
        StartHere(b, report);
        var byArea = report.Findings.GroupBy(f => ReportAreas.Of(f.Id)).ToDictionary(g => g.Key, g => (IReadOnlyList<Finding>)g.ToList());
        foreach (var area in ReportAreas.Ordered)
        {
            var findings = byArea.GetValueOrDefault(area) ?? [];
            if (area == ReportAreas.Other && findings.Count == 0)
            {
                continue;
            }

            Area(b, area, findings, report.Skipped);
        }

        Coverage(b, report.Skipped);
        Appendix(b, report);
        b.Append("</main>\n<footer class=\"wrap\">Generated by <a href=\"https://elevate.reothor.no/audit.html\">elevate-audit</a>, the standing-access companion to Elevate.")
         .Append(report.Tool.Version == "sample" ? " Sample data is fictional." : string.Empty)
         .Append("</footer>\n<script>\n").Append(Script.TrimEnd()).Append("\n</script>\n</body>\n</html>\n");
        return b.ToString();
    }

    private static void Header(StringBuilder b, AuditReport report, string tenantName)
    {
        b.Append("<header class=\"report-header\"><div class=\"wrap\">\n<p class=\"eyebrow\">elevate-audit · standing privileged access</p>\n");
        b.Append("<h1>").Append(E(tenantName)).Append("</h1>\n<ul class=\"meta\">\n");
        Meta(b, "Tenant id", report.Tenant.Id);
        Meta(b, "Scanned by", report.Account);
        Meta(b, "Scanned at", report.ScannedAt.ToString("yyyy-MM-dd HH:mm 'UTC'", CultureInfo.InvariantCulture));
        Meta(b, "Tool", $"{report.Tool.Name} {report.Tool.Version}");
        b.Append("</ul>\n");

        var verdict = ReportAreas.VerdictFor(tenantName, report.AllFindings, report.Skipped);
        b.Append("<p class=\"verdict\"><strong>").Append(E(verdict.Head)).Append("</strong>");
        if (verdict.Tail is not null)
        {
            b.Append(' ').Append(E(verdict.Tail));
        }

        b.Append("</p>\n");
        if (report.Hidden > 0)
        {
            b.Append("<p class=\"muted\">").Append(E($"{RenderText.Findings(report.Hidden)} below --min-severity {report.Options.MinSeverity} hidden")).Append("</p>\n");
        }

        b.Append("<div class=\"tiles\">\n");
        var all = report.AllFindings.GroupBy(f => ReportAreas.Of(f.Id)).ToDictionary(g => g.Key, g => (IReadOnlyList<Finding>)g.ToList());
        foreach (var area in ReportAreas.Ordered)
        {
            var findings = all.GetValueOrDefault(area) ?? [];
            if (area == ReportAreas.Other && findings.Count == 0)
            {
                continue;
            }

            Tile(b, area, findings, report.Skipped);
        }

        CoverageTile(b, report.Skipped);
        b.Append("</div>\n</div></header>\n");
    }

    private static void Tile(StringBuilder b, ReportArea area, IReadOnlyList<Finding> findings, IReadOnlyList<SkippedSource> skipped)
    {
        var state = ReportAreas.StateOf(area, findings, skipped);
        var pillClass = state switch
        {
            AreaState.Critical => "pill critical",
            AreaState.Attention => "pill attention",
            AreaState.Clean => "pill clean",
            _ => "pill",
        };
        b.Append("<a class=\"tile\" href=\"#").Append(area.Id).Append("\"><div class=\"head\"><span class=\"name\">").Append(E(area.Name)).Append("</span><span class=\"").Append(pillClass).Append("\">").Append(ReportAreas.StateLabel(state)).Append("</span></div>");
        b.Append("<div class=\"counts\">");
        if (state != AreaState.NotScanned)
        {
            foreach (var severity in new[] { Severity.High, Severity.Medium, Severity.Low, Severity.Info })
            {
                var n = findings.Count(f => f.Severity == severity);
                if (n > 0)
                {
                    var s = severity.ToString().ToLowerInvariant();
                    b.Append("<span><span class=\"n ").Append(s).Append("\">").Append(n.ToString(CultureInfo.InvariantCulture)).Append("</span> <span class=\"unit\">").Append(s).Append("</span></span>");
                }
            }
        }

        if (ReportAreas.UnderCounts(area, skipped))
        {
            b.Append("<span class=\"pill skipped\">under-counts</span>");
        }

        b.Append("</div><p class=\"line\">").Append(E(ReportAreas.Sentence(area, findings, skipped))).Append("</p></a>\n");
    }

    private static void CoverageTile(StringBuilder b, IReadOnlyList<SkippedSource> skipped)
    {
        var n = skipped.Count;
        b.Append("<a class=\"tile\" href=\"#coverage\"><div class=\"head\"><span class=\"name\">Coverage</span>")
         .Append(n == 0 ? "<span class=\"pill clean\">Complete</span>" : $"<span class=\"pill skipped\">{n} skipped</span>").Append("</div><div class=\"counts\">");
        if (n > 0)
        {
            b.Append("<span><span class=\"n skipped\">").Append(n.ToString(CultureInfo.InvariantCulture)).Append("</span> <span class=\"unit\">skipped</span></span>");
        }

        b.Append("</div><p class=\"line\">").Append(E(ReportAreas.Sentence(ReportAreas.Coverage, [], skipped))).Append("</p></a>\n");
    }

    private static void StartHere(StringBuilder b, AuditReport report)
    {
        var high = report.Findings.Where(f => f.Severity == Severity.High).ToList();
        b.Append("<section class=\"section-title\" id=\"start-here\"><div><h2>Start here</h2>");
        if (high.Count == 0)
        {
            b.Append("<p class=\"muted\">No high-severity findings. ").Append(E(report.Findings.Count == 0 ? "No standing privileged access was found." : "Review the medium and low findings below.")).Append("</p></div></section>\n");
            return;
        }

        b.Append("<p class=\"muted\">The high findings, grouped so one action fixes many.</p></div></section>\n<ol class=\"start\">\n");
        foreach (var group in high.GroupBy(f => f.Id))
        {
            if (GroupRollup.RollsUp(group.Key))
            {
                var (cards, rows) = GroupRollup.Build(group.Key, group.ToList());
                foreach (var card in cards)
                {
                    b.Append("<li data-search=\"").Append(E(Search(card))).Append("\" data-severity=\"high\"><span class=\"who\">").Append(E(card.Group.DisplayName)).Append(" · ").Append(E(card.Role.DisplayName)).Append(" on ").Append(E(card.Scope.DisplayName))
                     .Append(" <span class=\"muted\">· ").Append(E(ReportAreas.Plural(card.People, "person", "people"))).Append(card.NestedGroups > 0 ? E($" through {ReportAreas.Plural(card.NestedGroups, "nested group", "nested groups")}") : string.Empty).Append("</span></span>");
                    b.Append("<span class=\"what\">").Append(E(card.Remedy)).Append(" <a href=\"").Append(E(card.PortalUrl)).Append("\">Open in portal</a></span></li>\n");
                }

                foreach (var f in rows)
                {
                    StartItem(b, f);
                }
            }
            else
            {
                foreach (var f in group)
                {
                    StartItem(b, f);
                }
            }
        }

        b.Append("</ol>\n");
    }

    private static void StartItem(StringBuilder b, Finding f)
    {
        b.Append("<li data-search=\"").Append(E(Search(f))).Append("\" data-severity=\"high\"><span class=\"who\">").Append(E(f.Principal.DisplayName)).Append(f.Principal.IsGuest ? " <span class=\"pill\">guest</span>" : string.Empty)
         .Append(" · ").Append(E(f.Role.DisplayName)).Append(" on ").Append(E(f.Scope.DisplayName)).Append("</span>");
        if (f.Via.Count > 0)
        {
            b.Append("<span class=\"path\">via ").Append(E(string.Join(" ← ", f.Via.Select(v => v.DisplayName)))).Append("</span>");
        }

        b.Append("<span class=\"what\">").Append(E(f.Remedy)).Append(" <a href=\"").Append(E(f.PortalUrl)).Append("\">Open in portal</a></span></li>\n");
    }

    private static void Area(StringBuilder b, ReportArea area, IReadOnlyList<Finding> findings, IReadOnlyList<SkippedSource> skipped)
    {
        var open = findings.Any(f => f.Severity == Severity.High);
        b.Append("<details class=\"area\"").Append(open ? " open" : string.Empty).Append("><summary id=\"").Append(area.Id).Append("\">").Append(Caret).Append("<h2>").Append(E(area.Name)).Append("</h2>");
        foreach (var severity in new[] { Severity.High, Severity.Medium, Severity.Low, Severity.Info })
        {
            var n = findings.Count(f => f.Severity == severity);
            if (n > 0)
            {
                var s = severity.ToString().ToLowerInvariant();
                b.Append("<span class=\"pill ").Append(s).Append("\">").Append(n.ToString(CultureInfo.InvariantCulture)).Append(' ').Append(s).Append("</span>");
            }
        }

        if (ReportAreas.NotScannedReason(area, skipped) is not null)
        {
            b.Append("<span class=\"pill\">Not scanned</span>");
        }

        if (ReportAreas.UnderCounts(area, skipped))
        {
            b.Append("<span class=\"pill skipped\">under-counts</span>");
        }

        b.Append("</summary>\n<p class=\"area-desc\">").Append(E(area.Description));
        if (ReportAreas.NotScannedReason(area, skipped) is { } reason)
        {
            b.Append(' ').Append(E(reason));
        }

        b.Append("</p>\n");
        if (findings.Count == 0)
        {
            b.Append("<p class=\"area-desc\">").Append(E(ReportAreas.Sentence(area, findings, skipped))).Append("</p>\n");
        }

        foreach (var group in findings.GroupBy(f => (f.Id, f.Severity)))
        {
            Rule(b, group.Key.Id, group.Key.Severity, group.ToList(), skipped);
        }

        b.Append("</details>\n");
    }

    private static void Rule(StringBuilder b, string code, Severity severity, IReadOnlyList<Finding> findings, IReadOnlyList<SkippedSource> skipped)
    {
        var s = severity.ToString().ToLowerInvariant();
        var (cards, rows) = GroupRollup.RollsUp(code) ? GroupRollup.Build(code, findings) : (Array.Empty<RollupCard>(), findings);
        var count = cards.Count > 0
            ? $"{ReportAreas.Plural(cards.Count, "group", "groups")} · {ReportAreas.Plural(cards.Sum(c => c.People), "person", "people")}{(rows.Count > 0 ? $" · {ReportAreas.Plural(rows.Count, "direct finding", "direct findings")}" : string.Empty)}"
            : RenderText.Findings(findings.Count);
        b.Append("<details class=\"rule\" id=\"").Append(E(code.ToLowerInvariant())).Append('-').Append(s).Append("\" data-severity=\"").Append(s).Append("\" open><summary>").Append(Caret)
         .Append("<h3>").Append(E(code)).Append("</h3><span class=\"pill ").Append(s).Append("\">").Append(s).Append("</span><span class=\"desc\">").Append(E(RuleDescription(code))).Append("</span><span class=\"count\">").Append(E(count)).Append("</span></summary>\n");

        var unreadable = skipped.Any(x => string.Equals(x.Source, "groups", StringComparison.OrdinalIgnoreCase) && x.Reason.Contains("could not be read", StringComparison.OrdinalIgnoreCase));
        foreach (var card in cards)
        {
            Card(b, card, unreadable);
        }

        if (rows.Count > 0)
        {
            Table(b, rows);
        }

        b.Append("</details>\n");
    }

    private static void Card(StringBuilder b, RollupCard card, bool unreadableGroups)
    {
        b.Append("<div class=\"group\" data-search=\"").Append(E(Search(card))).Append("\"><div class=\"title\"><span class=\"who\">").Append(E(card.Group.DisplayName)).Append("</span><span class=\"pill\">group</span><span class=\"muted\">grants</span><span class=\"who\">").Append(E(card.Role.DisplayName)).Append("</span><span class=\"muted\">on ").Append(E(card.Scope.DisplayName)).Append(" to ").Append(E(ReportAreas.Plural(card.People, "person", "people")))
         .Append(card.NestedGroups > 0 ? E($" through {ReportAreas.Plural(card.NestedGroups, "nested group", "nested groups")}") : " directly").Append("</span></div>\n");
        b.Append("<p class=\"what\">").Append(E(card.Remedy)).Append(" <a href=\"").Append(E(card.PortalUrl)).Append("\">Open in portal</a></p>\n");
        if (unreadableGroups)
        {
            b.Append("<p class=\"what\">Some nested groups could not be read; their members are missing.</p>\n");
        }

        var diagram = GroupRollup.Diagram(card);
        b.Append("<div class=\"body\"><div><span class=\"label\">Membership</span>").Append(GroupRollup.Outline(card)).Append("</div>");
        if (diagram is not null)
        {
            b.Append("<div class=\"diagram\"><span class=\"label\">How the groups nest</span>").Append(diagram).Append("</div>");
        }

        b.Append("</div>\n");
        if (card.Members.Count > 0)
        {
            b.Append("<details class=\"members\" open><summary>").Append(Caret).Append("People reached (").Append(card.Members.Count.ToString(CultureInfo.InvariantCulture)).Append(")</summary>\n<div class=\"table-scroll\"><table><thead><tr><th>Person</th><th>Through</th><th>Remedy</th></tr></thead><tbody>\n");
            foreach (var f in card.Members)
            {
                b.Append("<tr data-search=\"").Append(E(Search(f))).Append("\"><td>").Append(E(f.Principal.DisplayName)).Append(f.Principal.IsGuest ? " <span class=\"pill\">guest</span>" : string.Empty);
                if (f.Principal.UserPrincipalName is { } upn)
                {
                    b.Append("<br /><span class=\"muted\">").Append(E(upn)).Append("</span>");
                }

                b.Append("</td><td class=\"path\">").Append(f.Via.Count == 0 ? "direct" : E(string.Join(" ← ", f.Via.Select(v => v.DisplayName)))).Append("</td><td>").Append(E(f.Remedy)).Append(" <a href=\"").Append(E(f.PortalUrl)).Append("\">Open in portal</a></td></tr>\n");
            }

            b.Append("</tbody></table></div></details>\n");
        }

        b.Append("</div>\n");
    }

    private static void Table(StringBuilder b, IReadOnlyList<Finding> rows)
    {
        b.Append("<div class=\"table-scroll\"><table><thead><tr><th>Principal</th><th>Role</th><th>Scope</th><th>How</th><th>Remedy</th></tr></thead><tbody>\n");
        foreach (var f in rows)
        {
            b.Append("<tr data-search=\"").Append(E(Search(f))).Append("\"><td>").Append(E(f.Principal.DisplayName));
            if (f.Principal.UserPrincipalName is { } upn)
            {
                b.Append("<br /><span class=\"muted\">").Append(E(upn)).Append("</span>");
            }

            if (f.Principal.Type == PrincipalType.Group)
            {
                b.Append(" <span class=\"pill\">group</span>");
            }

            if (f.Principal.IsGuest)
            {
                b.Append(" <span class=\"pill\">guest</span>");
            }

            b.Append("</td><td>").Append(E(f.Role.DisplayName)).Append("<br /><span class=\"muted\">").Append(E(f.Role.System.ToString())).Append("</span></td>");
            b.Append("<td>").Append(E(f.Scope.DisplayName)).Append("<br /><span class=\"muted\">").Append(E(Humanize(f.Scope.Kind))).Append("</span></td>");
            b.Append("<td>");
            if (f.Via.Count == 0)
            {
                b.Append("<span class=\"muted\">direct</span>");
            }
            else
            {
                b.Append("<details><summary>through ").Append(f.Via.Count.ToString(CultureInfo.InvariantCulture)).Append(f.Via.Count == 1 ? " group" : " groups").Append("</summary><span class=\"path\">").Append(E(string.Join(" ← ", f.Via.Select(v => v.DisplayName)))).Append("</span></details>");
            }

            b.Append("</td><td>").Append(E(f.Remedy)).Append(" <a href=\"").Append(E(f.PortalUrl)).Append("\">Open in portal</a></td></tr>\n");
        }

        b.Append("</tbody></table></div>\n");
    }

    private static void Coverage(StringBuilder b, IReadOnlyList<SkippedSource> skipped)
    {
        b.Append("<details class=\"area\"").Append(skipped.Count > 0 ? " open" : string.Empty).Append("><summary id=\"coverage\">").Append(Caret).Append("<h2>Coverage</h2>")
         .Append(skipped.Count == 0 ? "<span class=\"pill clean\">Complete</span>" : $"<span class=\"pill skipped\">{skipped.Count} skipped</span>").Append("</summary>\n<p class=\"area-desc\">").Append(E(ReportAreas.Coverage.Description)).Append("</p>\n");
        b.Append("<div class=\"table-scroll\"><table><thead><tr><th>Source</th><th>State</th><th>What it means</th></tr></thead><tbody>\n");
        var azureSkipped = ReportAreas.Has(skipped, "azure");
        foreach (var (source, name, note) in CoverageSources)
        {
            var reasons = skipped.Where(s => string.Equals(s.Source, source, StringComparison.OrdinalIgnoreCase)).Select(s => s.Reason).ToList();
            if (source == "azure-management-groups" && azureSkipped && reasons.Count == 0)
            {
                reasons.Add("Not scanned because Azure was skipped.");
            }

            b.Append("<tr><td>").Append(E(name)).Append("</td><td>").Append(reasons.Count == 0 ? "<span class=\"pill read\">read</span>" : "<span class=\"pill skipped\">skipped</span>")
             .Append("</td><td class=\"muted\">").Append(E(reasons.Count == 0 ? note : string.Join(" ", reasons))).Append("</td></tr>\n");
        }

        b.Append("</tbody></table></div>\n</details>\n");
    }

    private static void Appendix(StringBuilder b, AuditReport report)
    {
        b.Append("<details class=\"appendix\" id=\"appendix\"><summary>").Append(Caret).Append("<h2>Appendix</h2><span class=\"muted\">Options, scopes requested, evidence ids</span></summary>\n<p>Options: all roles ").Append(report.Options.AllRoles ? "on" : "off").Append("; minimum severity ").Append(E(report.Options.MinSeverity)).Append("; ignored rules: ").Append(report.Options.Ignored.Count == 0 ? "none" : E(string.Join(", ", report.Options.Ignored))).Append(".</p>\n");
        b.Append("<p>Read-only Microsoft Graph scopes requested: ").Append(report.ScopesRequested.Count == 0 ? "none recorded" : string.Join(", ", report.ScopesRequested.Select(s => "<code>" + E(s) + "</code>"))).Append(". Nothing was written to the tenant.</p>\n");
        b.Append("<p>This report contains personal data (names and sign-in names of people who hold roles). Handle it as you would any access review.</p>\n<details><summary>Evidence ids</summary><div class=\"table-scroll\"><table><thead><tr><th>Rule</th><th>Principal id</th><th>Assignment id</th><th>Start</th><th>End</th><th>Type</th></tr></thead><tbody>\n");
        foreach (var f in report.Findings)
        {
            b.Append("<tr><td>").Append(E(f.Id)).Append("</td><td><code>").Append(E(f.Principal.Id)).Append("</code></td><td><code>").Append(E(f.Evidence.AssignmentId)).Append("</code></td><td>").Append(E(Date(f.Evidence.StartDateTime))).Append("</td><td>").Append(E(Date(f.Evidence.EndDateTime))).Append("</td><td>").Append(E(f.Evidence.AssignmentType?.ToString() ?? f.Evidence.MemberType ?? "—")).Append("</td></tr>\n");
        }

        b.Append("</tbody></table></div></details></details>\n");
    }

    private static string RuleDescription(string code) => code.ToUpperInvariant() switch
    {
        "ENTRA-USER-PERMANENT" => "A user holds a permanent active Entra role directly",
        "ENTRA-GROUP-PERMANENT" => "A group holds a permanent active Entra role",
        "ENTRA-GROUP-NOT-PIM" => "A role-assignable group carrying a role is not onboarded to PIM for Groups",
        "ENTRA-GROUP-NOT-ASSIGNABLE" => "A role is assigned to a group that is not role-assignable",
        "GROUP-MEMBER-PERMANENT" => "A group managed by PIM for Groups still has a permanent member or owner",
        "AZURE-PERMANENT" => "A permanent privileged Azure role assignment",
        "SP-PERMANENT" => "A service principal or managed identity holds a permanent privileged role",
        "GUEST-PERMANENT" => "A guest holds a permanent privileged role",
        "ELIGIBLE-NO-END" => "An eligibility has no end date",
        "GA-COUNT" => "Fewer than 2 or more than 5 people can become Global Administrator",
        _ => string.Empty,
    };

    private static string Search(Finding f) =>
        string.Join(' ', new[] { f.Principal.DisplayName, f.Principal.UserPrincipalName, f.Role.DisplayName, f.Scope.DisplayName }.Concat(f.Via.Select(v => v.DisplayName)).Where(s => !string.IsNullOrEmpty(s))).ToLowerInvariant();

    private static string Search(RollupCard card) =>
        string.Join(' ', new[] { card.Group.DisplayName, card.Role.DisplayName, card.Scope.DisplayName }.Concat(card.Members.Select(Search))).ToLowerInvariant();

    private static void Meta(StringBuilder b, string label, string value) =>
        b.Append("<li>").Append(E(label)).Append("<strong>").Append(E(value)).Append("</strong></li>\n");

    private static string Humanize(ScopeKind kind) => kind switch
    {
        ScopeKind.AdministrativeUnit => "administrative unit",
        ScopeKind.ManagementGroup => "management group",
        ScopeKind.ResourceGroup => "resource group",
        _ => kind.ToString().ToLowerInvariant(),
    };

    private static string Date(DateTimeOffset? value) => value?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) ?? "—";

    private static string E(string? text) => WebUtility.HtmlEncode(text ?? string.Empty);
}
