<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Elevate.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\EntraBuiltInRoles.json" LogicalName="Elevate.Core.Resources.EntraBuiltInRoles.json" />
  </ItemGroup>

</Project>
